apiVersion: meta.mxp.upbound.io/v1alpha1
kind: ControlPlaneSource
metadata:
  name: controlplane-blue
  annotations:
    meta.upbound.io/company: Acme Inc.
spec:
  # Optional paramaters.
  #
  # rootPath tells where to scan recursively where only YAML files are included.
  rootPath: /
  #
  #
  # (Future) Pull secrets from external sources like Vault.
  # externalResources:
  #   - source:
  #       type: Vault
  #       vault:
  #         url: https://local.acme.org/vault/pull-secret
  #     type: Secret
  #     secret:
  #       metadata:
  #         name: internal-pull-secret
  #         namespace: upbound-system